---
- name: SISOP | Reboot Server
  ansible.builtin.reboot:
    msg: "Reboot initiated by Ansible for kernel updates"
    connect_timeout: 5
    reboot_timeout: 300
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: uptime
  regsiter: reboot-output
  tags:
   - server-reboot

- name: SISOP | Debug reboot server
  ansible.builtin.debug:
    msg: "{{ reboot-output }}"
  tags:
    - server-reboot
...