---
# tasks file for nginx
- name: YUM | Installing epel-repository on {{ ansible_distribution }}
  ansible.builtin.shell: 
     cmd: sudo amazon-linux-extras install epel -y
  when: ansible_distribution == "Amazon"
 
- name: SYSTEM | Configuring Nginx repository on {{ ansible_distribution }}
  ansible.builtin.copy:
    src: nginx.repo
    dest: /etc/yum.repos.d/nginx.repo
    owner: root
    group: root
    mode: 0644
  when: ansible_distribution == "CentOS" or ansible_distribution == "OracleLinux"
  tags: 
    - repo_nginx

- name: SYSTEM | Configuring Nginx repository on {{ ansible_distribution }}
  ansible.builtin.copy:
    src: nginx_amzn2.repo
    dest: /etc/yum.repos.d/nginx.repo
    owner: root
    group: root
    mode: 0644
  when: ansible_distribution == "Amazon"

- name: SYSTEM | Updating System
  ansible.builtin.yum:
    name: "*"
    state: latest
    update_cache: yes
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"
  #when: ansible_distribution == "CentOS" or ansible_distribution == "OracleLinux" 
  tags:
    - update_system

- name: NGINX | Installing nginx (latest version)
  ansible.builtin.yum:
     name: ['nginx.x86_64']
     state: latest
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"
  when: ansible_distribution == "CentOS" or ansible_distribution == "OracleLinux"
  tags:
    - install_nginx

- name: NGINX | Creating directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: 700
    owner: root
    group: root
  with_items: 
    - /etc/nginx/features
    - /etc/nginx/cert
    - /etc/nginx/vhosts.d

- name: NGINX | Copying files
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
    force: yes
    backup: yes
  with_items:
    - { src: 'nginx.conf', dest: '/etc/nginx/nginx.conf'}
    - { src: 'gzip.conf', dest: '/etc/nginx/features/gzip.conf'}
    - { src: 'ssl.conf', dest: '/etc/nginx/features/ssl.conf'}
    - { src: 'vhost.example', dest: '/etc/nginx/vhosts.d/vhost.example'}
    - { src: 'dhparam.pem', dest: '/etc/nginx/cert/dhparam.pem'}
  tags: copy_nginx_files
...
