---
- name: Ansible Temp Playbook for tests
  hosts: debian:redhat
  become: true
  roles:
    - 23-temp
    - role: 11-ansibleConditionalBool
      vars:
        http_port: 8080
        username: adminssc
        backup: false
        snapshot: true
      when: ansible_facts['os_family'] == 'Debian' or  ansible_facts['os_family'] == 'RedHat'
      tags:
        - teste
...