# https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_blocks.html
---
- block:
   - name: Debug Mode
     ansible.builtin.debug:
       msg: "#### EXECUTADO NORMALMENTE ###"
     tags:
       - print-debug
  
   - name: Simulando erros
     ansible.builtin.shell:
       cmd: ./configure
       chdir: /tmp
    
   - name: Debug Mode 2
     ansible.builtin.debug:
       msg: "#### NUNCA SERA EXECUTADO ###"
     tags:
       - print-debug
  
  rescue:
     - name: Debug Mode 3
       ansible.builtin.debug:
        msg: "ERROR - FALHA NO TARGET {{ inventory_hostname }}"
       tags:
         - print-debug
  # You can also add an always section to a block. Tasks in the always section run no matter what the task status of the previous block is. Block with always section
  always: 
     - name: SISOP | Update System
       ansible.builtin.dnf:
         name: "*"
         state: latest
... 

