# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/yum_module.html
# https://www.toptechskills.com/ansible-tutorials-courses/ansible-yum-module-tutorial-examples/
# https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_tags.html
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/dnf_module.html
# https://4sysops.com/archives/ansible-yum-module-install-the-rhelcentos-packages/
---
- name: Update Redhat Distribution | By YUM
  ansible.builtin.yum:
     name: "*"
     state: latest
     update_cache: yes
     nobest: true # Set best option to False, so that transactions are not limited to best candidates only.
     bugfix: true #If set to true, and state=latest then only installs updates that have been marked bugfix related.
     security: false  #If set to true, and state=latest then only installs updates that have been marked security related.
  when: ansible_distribution == 'CentOS' or ansible_os_family == 'RedHat'
  register: yum_output
  tags:
   - update-redhat

- name: Update Kernel | By YUM
  ansible.builtin.yum:
    name: 'kernel*'
    state: latest
    nobest: true
    update_only: yes
    update_cache: true
  when: ansible_distribution == 'CentOS' or ansible_os_family == 'RedHat'
  tags:
   - update-redhat-kernel

- name: Update All Packages | By Shell
  ansible.builtin.shell:
   cmd: yum update --nobest -y
  register: shell_output
  when: ansible_distribution == 'CentOS' or ansible_os_family == 'RedHat'
  tags:
   - update-redhat-shell

- name: Print output Update by Shell
  ansible.builtin.debug: 
   var: shell_output
  tags:
   - update-redhat-shell

- name: Print output Update Redhat | Debug mode with var
  ansible.builtin.debug: 
   var: yum_output
  tags:
   - print-debug-output
   - update-redhat

- name: Print output of update REDHAT | Debug mode with msg
  ansible.builtin.debug:
     msg: "{{ yum_output }}"
  tags:
   - print-debug-output
   - update-redhat
...