---
- name: Ping all Server 
  ansible.builtin.ping:

- name: Ping All Server by shell
  ansible.builtin.shell: ping -c 1 -w 2 {{ ansible_host }}
  #delegate_to: localhost
  ignore_errors: true
  register: result

- name: Print result of Ping All Server by shell
  ansible.builtin.debug:
    msg: "{{ result }}"

