---
- name: SYSTEM | Copy files
  ansible.builtin.copy:
     src: "{{ item.src }}"
     dest: "{{ item.dest }}"
     owner: "{{ item.owner }}"
     mode: "{{ item.mode | default(omit) }}"
     group: "{{ item.group }}"
  register: lista
  with_items:
    - { src: 'file1.txt', dest: '/tmp/', owner: 'adminssc', mode: '640', group: 'adminssc' }
    - { src: 'file2.txt', dest: '/tmp/', owner: 'adminssc', group: 'adminssc' }
    - { src: 'file3.txt', dest: '/tmp/', owner: 'adminssc', mode: '640', group: 'adminssc' }

- name: Debug Copy files
  ansible.builtin.debug:
     var: "{{ item}}"
  with_items: "{{ lista }}"

- name: Example from an Ansible Playbook
  ansible.builtin.ping:
  register: output_ping
  delegate_to: 127.0.0.1

- name: Create multiple files
  ansible.builtin.file:
    path: "/tmp/files{{ outer_item }}.txt"
    state: touch
  loop: "{{ range(5, 10) }}"
  loop_control:
   loop_var: outer_item
...