---
# handlers file for ansible-firewalld
- name: firewalld reload
  ansible.builtin.command:
    cmd: firewall-cmd --reload
  ignore_errors: true

#- name: Start and enabled the Firewalld
#  ansible.builtin.systemd:
#    name: firewalld
#    state: reload
#    daemon_reload: true
#  ignore_errors: true