# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/user_module.html
---
- name: User | Remove User 
  ansible.builtin.user:
     user: "{{ item.name }}"
     state: absent
     remove: yes
  loop:
    - {{ name: 'dvmelo', comment: 'Duarte Vieira de Melo' }}
    - {{ name: 'pcardoso', comment: 'Pedro Cardoso - DBA'}}
    - {{ name: 'lpsa', comment: 'Leonardo Sá - DBA' }} 
  ignore_errors: true
  tags:
    - delete-user

- name: User | Create User 
  ansible.builtin.user:
     user: "{{ item.name }}"
     state: present
     group: "wheel"
     shell: /bin/bash
     system: true
     password: "{{ item.password }}"
     comment: "{{ item.comment }}"
  loop:
    - {{ name: 'dvmelo', comment: 'Duarte Vieira de Melo', password: 'qwe1234' }}
    - {{ name: 'pcardoso', comment: 'Pedro Cardoso - DBA', password: 'qwe1234'}}
    - {{ name: 'lpsa', comment: 'Leonardo Sá - DBA', password: 'qwe1234' }} 
  tags:
    - add-user
...