# https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_variables.html
---
- name: Debug variavel local
  ansible.builtin.debug:
     msg: "{{ message }}"
  tags:
   - variable-test

- name: Debug variavel pelo defautls | {{ message1 }}
  ansible.builtin.debug:
     msg: "{{ message1 }}"
  tags:
   - variable-test

- name: DNF | Install packages
  ansible.builtin.dnf:
    name: "{{ packages }}"
    state: latest
  tags:
   - install-packages
...