---
- name: APT | Installing Mysql and dependencies
  ansible.builtin.apt:
     name: "{{ item }}"
     state: present
     update_cache: yes
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"
  with_items: "{{ package }}"
  ignore_errors: true
  tags:
   - apt-mysql
...