# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/file_module.html
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/template_module.html
---
- block:
  - name: Create a directory if it does not exist
    ansible.builtin.file:
      path: /tmp/ipset/
      state: directory
      mode: '0644'
      owner: root
      group: root
    become: true
    become_user: root
  

  - name: Add entry to IPSet
    #debug: msg={{ ipset_rule.name }}{{ entry }}
    #command: firewall-cmd --permanent --ipset={{ ipset_rule.name }} --add-entry={{ entry }}
    template:
      src: ipset.xml.j2
      dest: /tmp/ipset/{{ item.name }}.xml
      owner: root
      group: root
      mode: '0644' 
      backup: yes
    with_items: "{{ ipset_rules }}"
    become: true
    become_user: root
     # loop_control:
     #   loop_var: entry
  rescue:
    - name: Debug Mode 3
      ansible.builtin.debug:
        msg: "ERROR - FALHA NO TARGET {{ inventory_hostname }}"
      tags:
        - print-debug
  # You can also add an always section to a block. Tasks in the always section run no matter what the task status of the previous block is. Block with always section
  always: 
     - name: SISOP | Update System OracleLinux
       ansible.builtin.dnf:
         name: "*"
         update_cache: yes
         nobest: true # Set best option to False, so that transactions are not limited to best candidates only.
         state: latest
       register: dnf_output
       when: ansible_facts['distribution'] == "OracleLinux" or ansible_facts['distribution'] == "CentOS"
       tags:
        - upgdate-centos
    
     - name: SISOP | Update System Debian
       ansible.builtin.apt:
         name: "*"
         state: latest
         update_cache: yes
       register: apt_output
       when: ansible_distribution == 'Ubuntu'
       tags:
         - update-debian
...