---
- name: APT | Update update_cache
  ansible.builtin.apt:
    update_cache: yes
  #environment:
    #http_proxy: "{{ http_proxy }}"
    #https_proxy: "{{ https_proxy }}"
  #when: ansible_distribution in ["Ubuntu", "Debian"]

- name: APT | Update Systems
  ansible.builtin.apt:
    name: "*"
    state: latest
  #environment:
    #http_proxy: "{{ http_proxy }}"
    #https_proxy: "{{ https_proxy }}"
  #when: ansible_distribution in ["Ubuntu", "Debian"]
...