---
# tasks file for 22-roles
- name: DNF | Update Systems
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"
  import_tasks: redhat.yml
  when: ansible_distribution in ["OracleLinux", "Red Hat Enterprise Linux", "CentOS"]

- name: APT | Update update_cache
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"
  import_tasks: debian.yml
  when: ansible_distribution in ["Ubuntu", "Debian"]
...
