---
# tasks file for 22-roles
- name: DNF | Update Systems
  ansible.builtin.dnf:
    name: "*"
    state: latest
    update_cache: yes
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"
  when: ansible_distribution in ["OracleLinux", "Red Hat Enterprise Linux", "CentOS"]

- name: APT | Update update_cache
  ansible.builtin.apt:
    update_cache: yes
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"
  when: ansible_distribution in ["Ubuntu", "Debian"]

- name: APT | Update Systems
  ansible.builtin.apt:
    name: "*"
    state: latest
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"
  when: ansible_distribution in ["Ubuntu", "Debian"]

...
