---
- name: DNF | Update Systems
  ansible.builtin.dnf:
    name: "*"
    state: latest
    update_cache: yes

- name: DNF | Update All Packages
  ansible.builtin.shell:
   cmd: yum update --nobest -y
  changed_when: false

- name: DNF | Remove old kernels
  ansible.builtin.shell:
     cmd: dnf remove --oldinstallonly --setopt installonly_limit=2 kernel -y
  become: true
  register: output_dnf
  ignore_errors: true
  changed_when: false
  tags:
   - boot-size
...