---
- name: Print a Message
  ansible.builtin.debug:
     msg: 'Utilizador: {{ username }} | Password: {{ Password }} | Shell: {{ shell }}'
  tags:
    - print-debug

- name: User | Add a User
  ansible.builtin.user:
     username: "{{ username }}"
     comment: "Create a user by Ansible playbook"
     shell: "{{ shell }}"
     home: "/home/{{ username }}"
     password: "{{ password }}"
  tags:
    - add-user-linux
...